# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- none

pool:
  vmImage: ubuntu-latest

steps:
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      echo 'Preparar ambiente' 
      sudo apt-get -y update
      sudo apt-get -y install curl 
      echo "deb https://dl.bintray.com/sbt/debian /" | sudo tee -a /etc/apt/sources.list.d/sbt.list
      sudo apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv 2EE0EA64E40A89B84B2DF73499E82A75642AC823
      sudo apt-get -y update
      sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
      sudo apt-get -y update
      sudo apt-get -y install sbt git debianutils rpm ssh
      echo $(PIPELINES_SSH_KEY) | base64 -di > ~/temp.pem
      sudo chmod 600 ~/temp.pem
      echo 'Compilando app'
      git clone https://github.com/arielvega/proyecto-gcs
      cd proyecto-gcs
      sbt compile
      echo 'app  Compilada'
      echo 'Ejecutando pruebas unitarias'
      sbt test
      echo 'Pruebas unitarias ejecutadas'
      echo 'Ejecutando pruebas de integracion'
      sudo systemctl start docker
      sudo docker run -it -e POSTGRES_PASSWORD=gcs -e POSTGRES_USER=gcs -e POSTGRES_DB=gcs -p 127.0.0.1:5432:5432  postgres:9.5 &
      sbt "project gcsAppIT" test
      echo 'Pruebas de integracion ejecutadas'
      echo 'Empaquetando'
      sbt rpm:packageBin
      mv $(Agent.BuildDirectory)/s/proyecto-gcs/gcs-app/target/rpm/RPMS/noarch/gcs-app-2.8.x-1.noarch.rpm ~/gcs-app-2.8.x-1.noarch.rpm
      echo 'Empaquetado'
      echo 'Desplegar'
      #scp -o "StrictHostKeyChecking no" -i ~/temp.pem ~/gcs-app-2.8.x-1.noarch.rpm azureuser@40.74.228.20:.
